#ifndef __POK_KERNEL_GENERATED_DEPLOYMENT_H_
#define __POK_KERNEL_GENERATED_DEPLOYMENT_H_ 

#define POK_NEEDS_TIME       1
#define POK_NEEDS_THREADS    1
#define POK_NEEDS_PARTITIONS 1
#define POK_NEEDS_SCHED      1
#define POK_NEEDS_MIDDLEWARE 1
#define POK_NEEDS_PORTS_SAMPLING 1

#define POK_CONFIG_NB_THREADS       4
#define POK_CONFIG_NB_PARTITIONS    2

#define POK_CONFIG_PARTITIONS_SIZE  {120 * 1024,120 * 1024};
#define POK_CONFIG_PARTITIONS_NTHREADS {2,2}
#define POK_CONFIG_SCHEDULING_SLOTS {2000, 2000}
#define POK_CONFIG_SCHEDULING_MAJOR_FRAME 4000
#define POK_CONFIG_SCHEDULING_SLOTS_ALLOCATION {0,1}
#define POK_CONFIG_SCHEDULING_NBSLOTS 2

#define POK_CONFIG_NB_PORTS         2

#define POK_CONFIG_NB_ALLPORTS  2

#define POK_NEEDS_DEBUG


typedef enum
{
   dataout = 0,
   datain  = 1
}pok_ports_identitiers_t;

#endif
